# Generated by Django 3.0.1 on 2020-02-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
