# Generated by Django 3.0.1 on 2020-01-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.TextField()),
                ('To', models.TextField()),
                ('Departure_Date', models.TimeField()),
                ('Adults', models.IntegerField()),
                ('Children', models.IntegerField()),
            ],
        ),
    ]
