# Generated by Django 3.0.3 on 2020-02-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='Children',
        ),
        migrations.AddField(
            model_name='flights',
            name='Childrens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flights',
            name='Adults',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flights',
            name='Departure_Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='flights',
            name='From',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flights',
            name='To',
            field=models.CharField(max_length=50),
        ),
    ]
