# Generated by Django 3.0.2 on 2020-02-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabbing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pickup', models.CharField(max_length=150)),
                ('Drop', models.CharField(max_length=150)),
                ('File', models.FileField(upload_to='cabing/photo/')),
            ],
        ),
    ]
