# Generated by Django 3.0.2 on 2020-01-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pickup', models.CharField(max_length=150)),
                ('Drop', models.CharField(max_length=150)),
            ],
        ),
    ]
