# Generated by Django 3.0.2 on 2020-02-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabbing',
            name='File',
            field=models.FileField(upload_to='photo/'),
        ),
    ]
