# Generated by Django 3.0.2 on 2020-02-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabs', '0002_auto_20200210_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabbing',
            name='File',
            field=models.FileField(null=True, upload_to='photo/'),
        ),
    ]
