# Generated by Django 3.0.2 on 2020-01-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='Guest',
            field=models.SmallIntegerField(default=10),
        ),
    ]
