# Generated by Django 3.0.2 on 2020-02-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_hotel_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='Guest',
        ),
        migrations.AddField(
            model_name='hotel',
            name='Adults',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='childern',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
