# Generated by Django 3.0.2 on 2020-02-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_auto_20200208_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='Check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='Check_out',
            field=models.DateField(),
        ),
    ]
